language: python
dist: focal
python:
  - "3.10"

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot flask

script:
  - travis_wait 30 mvn install
  - chmod +x *
  - travis_wait 30 python3 opl.py   # Run the second script with a wait of 30 minutes
